#!/bin/sh

# Change to the directory containing this script
set -e
cd "$(dirname "$0")"

# Invoke dirplex running in this directory, loading the wsgidir.rc
# configuration file. The same configuration can be put in
# e.g. /etc/ashd/dirplex.d or in any .htrc file.
htparser plain:port=8080 -- dirplex -c ./wsgidir.rc .
